baseurl = "https://www.seanmooney.info"
languageCode = "en-ie"
title = "today i learned"
theme = "hugo-future-imperfect"
[params]
  description = "A blog and portfile of thing i discover day to day."
  mainIcon = "/img/hugo.png"

